### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by karmaniverous** [AykutSarac/github-rater#9]
I'm curious: what is the point of the 1.08 multiplier [here](https://github.com/AykutSarac/github-rater/blob/ae243db3badb2cdfd4afef32a65616819410471e/src/components/ResultSection/ResultsWrapper.tsx#L23)?

**Comment by AykutSarac** [comment]
Hello, sorry for the very late response. The multiplier was added as a result of testing the app with multiple top accounts at GitHub.

**Comment by karmaniverous** [comment]
Lot of empirical adjustments in there. No real argument with that... there really aren't many other alternatives out there to choose from. It IS an easy system to game, though... took me about a week to bring my score from 30-something up to 82.

On the flip side: "gaming the system" gave me very clear direction on how to improve my profile. Which was probably useful well above & beyond my GHR score.
